services:

  kafka:
    image: apache/kafka:latest
    container_name: central_kafka
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"  
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9093:9093"  # Puerto interno del controlador

  central:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: central_app
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CENTRAL_CP_PORT=5001
      - CENTRAL_API_PORT=8000
    ports:
      - "8000:8000"
      - "5001:5001"
    volumes:
      - ./app/data.json:/central/app/data.json
    restart: unless-stopped

networks:
  default:
    driver: bridge
